django/post/urls.py
from django.urls import path, include
from . import views

app_name = "post"

urlpatterns = [
    path('', views.get_img, name = "img_get"),
]

django/search_pic/urls.py
from django.urls import path, include
from . import views

app_name = "search"

urlpatterns = [
    path('', views.index, name = "pic_search"),
    path('auth/', views.auth, name = "pic_auth"),
    path('show/', views.show, name = "pic_show"),
]

django/upload/urls.py
from django.urls import path, include, re_path
from django.contrib import admin

from django.views.static import serve
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('post/', include('post.urls',namespace='post')),
    path('', include('search_pic.urls',namespace='search')),
    path('adminadmin/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}), 
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#staticを表示するために追加

django/post/models.py
from django.db import models

# Create your models here.
class FILENAME(models.Model):
    file_name = models.CharField(max_length=70)
    pwd = models.CharField(max_length=70)

    def __str__(self):
        return self.file_name

django/search_pic/models.py
from django.db import models

# Create your models here.

django/post/views.py
from django.shortcuts import render
import json
from django.http.response import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.core.files.storage import default_storage
from .models import FILENAME
#パスワード生成
import string
import secrets
import os
import glob

# Create your views here.
@csrf_exempt
def get_img(request):
    
    if request.method == "POST":
        # ← 受け取ったPOST画像データを保存
        if request.FILES["image_file"].name == "reset_data.jpeg":
            delete_img()
            FILENAME.objects.all().delete()
            ret = {"url": "全データ削除完了","pwd": "OK"}
            # JSONに変換して戻す
            return JsonResponse(ret)
        else:
            pwd = pass_gen()
            res, file_name = save(request.FILES["image_file"], pwd)
            res = request.build_absolute_uri(res)
            print(res)
            #データベースに保存
            new_data = FILENAME(file_name = file_name, pwd = pwd)
            new_data.save()
    
    else:  # ← methodが'POST'ではない = 最初のページ表示時の処理
        return render(request, "howto.html")

    ret = {"url": res,"pwd": pwd}

    # JSONに変換して戻す
    return JsonResponse(ret)

def save(data,pwd):
        file_name = default_storage.save(pwd + data.name, data)
        return default_storage.url(file_name), data.name

def pass_gen(size=12):
   chars = string.ascii_uppercase + string.ascii_lowercase + string.digits
   # 記号を含める場合
   # chars += '%&$#()'

   return ''.join(secrets.choice(chars) for x in range(size))

def delete_img():
    for file in glob.glob('/django/media/*.jpeg'):
        os.remove(file)

    for file in glob.glob('/django/media/*.jpg'):
        os.remove(file)

    for file in glob.glob('/django/media/*.txt'):
        os.remove(file)

    for file in glob.glob('/django/media/*.png'):
        os.remove(file)

    for file in glob.glob('/django/media/*.xlsx'):
        os.remove(file)

    for file in glob.glob('/django/media/*.pdf'):
        os.remove(file)

django/search_pic/views.py
from django.shortcuts import render, redirect
from post.models import FILENAME

from django.contrib import messages
from django.db.models import Q


# Create your views here.
def index(request):
    files = None
    keyword = request.GET.get('keyword')
    if keyword:
        files = FILENAME.objects.all()
        files = files.filter(
                 Q(file_name__icontains=keyword)
               )
        messages.success(request, '「{}」の検索結果'.format(keyword))
    return render(request, 'index.html', {'files': files, 'admin': False  })

def auth(request):
    pic = request.GET.get('pic')
    messages.success(request, '「{}」のパスワードを入力'.format(pic))
    return render(request, 'picAuth.html', {'picture': pic })

def show(request):
    try:
        pwd = request.POST["pwd"]
        pic = request.POST["pic"]
    except:
        pwd = None
        return redirect(request.build_absolute_uri()[:-6])

    if pic == "admin" and pwd == "adminPassword":
        messages.error(request, '全ての画像を表示します')
        files = FILENAME.objects.all()
        return render(request, 'index.html', {'files': files, 'admin': True })

    try:
        selected_file = FILENAME.objects.get(pwd = pwd)
        if pic == selected_file.file_name:
            return redirect(request.build_absolute_uri()[:-6] + '/media/' + pwd + selected_file.file_name)
        else:
            messages.error(request, 'パスワードが間違っています')
            files = None
            return render(request, 'index.html', {'files': files, 'admin': False })
    except:
        messages.error(request, 'パスワードが間違っています')
        files = None
        return render(request, 'index.html', {'files': files, 'admin': False  })
        

django/templates/howto.html
{% extends 'index.html' %}

{% block content %}
<style>
    #switch {
  display: block;
  list-style: none;
  padding: 0;
  margin: 0 auto;
  overflow: hidden;
  }
.btn {
  float: left;
  width: 200px;
  margin: 0 0 2rem 10px;
  padding: 5px;
  font-size: 1.6rem;
  text-align: center;
  background: #CCC;
  color: #FFF;
  border-bottom: 4px solid rgba(0, 0, 0, .2);
  }
.btn:hover {
  opacity: .8;
  cursor: pointer;
  }
.inactive { opacity: .5; }
.inactive:hover {
  opacity: .5;
  cursor: default;
  }
.boxDisplay { display: block; }
.boxNone { display: none; }
</style>

<div class = "box" style = "margin: 2rem 0rem">
<h1>
        以下のコード例のように、このページに画像をPOSTするとJSON形式で
    </h1>
        <code>
            {'url': 'http://127.0.0.1:8000/media/R35TkGquow61sample.jpeg', 'pwd': 'R35TkGquow61'}
        </code>
    <h1>
        以上の形式のレスポンスを返します。
    </h1>
    <h1>
        HOMEから直接画像をアップロードして、URLを発行することもできます。
    </h1>
    <h1>
      *画像データは毎週月曜日に定期削除されます。一時的に保存したいときにご使用ください。
    </h1>
</div>

<ul id="switch">
        <li id="Py">Python</li>
        <li id="G">Node.js</li>
</ul>


<div id = "Python">
    <pre class="brush: py">
        <code class="prettyprint linenums lang-python">
                import requests
                import json
                #POSTするURL設定
                post_url = "<今表示しているページのURL>"
                
                #POSTするファイルの読込
                files = { "image_file": open('./sample.jpeg', 'rb') }
                
                #POST送信
                response = requests.post(
                    post_url,
                    files = files,)
                
                print(json.loads(response.text))
        </code>
    </pre>
</div>

<div id = "Go">
        <pre class="brush: js">
            <code class="prettyprint linenums lang-python">
                    var request = require('request');
                    var fs = require('fs');

                    var url = '<今表示しているページのURL>';
                    var formData = {
                        'image_file': fs.createReadStream('./sample.jpeg'),
                    };

                    request.post({url:url, formData:formData}, function(err, response, body) {
                        if(err){
                        console.log(err)
                        }else{
                        console.log(body)
                        };
                    });
            </code>
        </pre>
    </div>



<script>
function clickSwitch() {
    'use strict';
    var isA = 0; // 現在地判定
    var btnA = document.getElementById('Py');
    var btnB = document.getElementById('G');
    var divA = document.getElementById('Python');
    var divB = document.getElementById('Go');
   
    function setState(isA) {
      btnA.className = (isA == 0) ? 'btn inactive' : 'btn'; // Aのとき非表示
      divA.className = (isA == 0) ? 'boxDisplay' : 'boxNone'; // Aのとき表示
      btnB.className = (isA == 1) ? 'btn inactive' : 'btn'; // Bのとき非表示
      divB.className = (isA == 1) ? 'boxDisplay' : 'boxNone'; // Bのとき表示
    }
    setState(0);
   
    btnA.addEventListener('click', function(){
      if (isA == 0) return;
      isA = 0;
      setState(0);
    });
    btnB.addEventListener('click', function(){
      if (isA == 1) return;
      isA = 1;
      setState(1);
    });
  };
  document.addEventListener("DOMContentLoaded", clickSwitch, false);
</script>
{% endblock %}

django/templates/index.html
<html>
<head>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-163315041-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-163315041-1');
</script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>画像アップローダー</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css">
    <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <link rel="icon" href="/static/icon/favicon.ico">
    <style type="text/css">
    * {
        box-sizing: border-box;
        margin: 0;
        padding: 0;
    }
    .nav{
    background:rgba(3, 17, 37, 0.48);
    font-color: white;
    box-shadow:0 2px 8px rgba(30,30,80,.3);
    left:0;
    line-height:1;
    position:fixed;
    top:0;
    width:100%;
    z-index:100;
    text-align:center;
    padding:1rem;
    }
    .input-content {
        width:50%; 
        height:40px;
        border-radius: 10px;
    }
    .input-content:focus {
    border: 2px solid #95bef5; 
    z-index: 10;
    outline: 0;
    }
    .btn-sticky {
    display: inline-block;
    padding: 0.5em 1em;
    text-decoration: none;
    background: #f7f7f7;
    border-left: solid 6px #ff7c5c;/*左線*/
    color: #ff7c5c;/*文字色*/
    font-weight: bold;
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.29);
    }
    .btn-sticky:active {
    box-shadow: inset 0 0 2px rgba(128, 128, 128, 0.1);
    transform: translateY(2px);
    }
    .box {
    padding: 0.2em 0.5em;
    margin: 10em 0;
    background: #d6ebff;
    box-shadow: 0px 0px 0px 10px #d6ebff;
    border: dashed 2px white;
    }
    .box p {
    margin: 0; 
    padding: 0;
    }
    ul {
    padding: 0;
    position: relative;
    width: 40%;
    text-align:center;
    margin: 3% 30%;
    }

    ul li {
    color: black;
    border-left: solid 8px orange;/*左側の線*/
    background: whitesmoke;/*背景色*/
    margin-bottom: 5px;/*下のバーとの余白*/
    line-height: 1.5;
    border-radius: 0 15px 15px 0;/*右側の角だけ丸く*/
    padding: 0.5em;
    list-style-type: none!important;
    }
    </style>
</head>
<body>
    <nav class="nav" role="navigation" aria-label="main navigation">
        <div class="container">
            <div id="navbar-menu" class="navbar-menu">
                <div class="navbar-start">
                    <img src="/static/icon/favicon.ico" width="60" height="60" >
                    <a class="navbar-item" style = "color:white;" href="{% url 'search:pic_search' %}">HOME</a>
                    <a class="navbar-item" style = "color:white;" href="{% url 'post:img_get' %}">使い方</a>
                </div>
            </div>
        </div>
    </nav>
    <div style = "height: 100px;"></div>

    {% if messages %}
    <div class="container" style="margin-top:1rem; width:60%;">
        <div class="notification is-info">
            <button class="delete" type="button"></button>
            {% for message in messages %}
            <p> {{ message }}</p>
            {% endfor %}
        </div>
    </div>
    {% endif %}

    {% block content %}

    <div style="font-size: 40px; text-align:center;">
    <form method="GET" action="{% url 'search:pic_search' %}" style = "margin-bottom: 1rem;">
        <input class="input-content" type="text" name="keyword" placeholder="探したい画像のキーワードを入力してください">
        <button type="submit" class="btn-sticky">検索</button>
    </form>
    </div>
    {% if admin %}
    <ul>
        {% for file in files %}
        <li><a href = "{{ path }}/media/{{ file.pwd }}{{ file.file_name }}">{{ file.file_name }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <ul>
            {% for file in files %}
            <li><a href = "{{ path }}/auth/?pic={{ file.file_name }}">{{ file.file_name }}</a></li>
            {% endfor %}
    </ul>
            
    <div class="box" style = "text-align: center; margin-top: 10px;">
    <p>画像をアップロード</p>
                <form action="{% url 'post:img_get' %}" method="POST" enctype="multipart/form-data">
                    <div id = "drag-drop-area">
                    <div class="drag-drop-inside">
                            <p class="drag-drop-info">ここにファイルをドロップ</p>
                            <p>または</p>
                    <input type="file" id="fileInput" name="image_file" multiple>
                    {% csrf_token %}
                    <input type="submit">
                    </div>
                    </div>
                </form>
            </div>
    </div>
    {% endif %}
    {% endblock %}
    <script>
        var fileArea = document.getElementById('drag-drop-area');
var fileInput = document.getElementById('fileInput');


fileArea.addEventListener('dragover', function(evt){
  evt.preventDefault();
  fileArea.classList.add('dragover');
});

fileArea.addEventListener('dragleave', function(evt){
    evt.preventDefault();
    fileArea.classList.remove('dragover');
});
fileArea.addEventListener('drop', function(evt){
    evt.preventDefault();
    fileArea.classList.remove('dragenter');
    var files = evt.dataTransfer.files;
    fileInput.files = files;
});
        </script>

    
    <script>
        // notificationを×押下で閉じれるように。
        for (const element of document.querySelectorAll('.notification > .delete')) {
            element.addEventListener('click', e => {
                e.target.parentElement.classList.add('is-hidden');
            });
        }
    
        // ナビバーの開閉を設定
        for (const element of document.querySelectorAll('.navbar-burger')) {
            const menuId = element.dataset.target;
            const menu = document.getElementById(menuId);
            element.addEventListener('click', e => {
                element.classList.toggle('is-active');
                menu.classList.toggle('is-active');
            });
        }
    
    </script>

</body>
</html>

django/templates/picAuth.html
{% extends 'index.html' %}

{% block content %}
<div style="font-size: 40px; text-align:center;">
<form method="POST" action="{% url 'search:pic_show' %}"　style = "margin-bottom: 1rem;">
        {% csrf_token %}
        <input class="input-content" type="text" name="pic" value={{ picture }} style = "margin-top: 1rem; ">
        <input class="input-content" type="password" name="pwd" placeholder="パスワードを入力" style = "margin-top: 1rem; ">
        <div><button type="submit" class="btn-sticky" style = "margin-top: 1rem; ">表示</button></div>
</form>
</div>
{% endblock %}